name: snowflake_ml_pipeline
version: "1.0.0"
config-version: 2

profile: snowflake_ml_pipeline

model-paths:
  - models
target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  snowflake_ml_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
