"""Load the LAMDA feature descriptions into Cloudflare R2 as Iceberg tables.

Reads ``data/lamda_feature_descriptions.json`` (generated by
``scripts/build_lamda_feature_descriptions.py``) and loads it with dlt into the
same R2 Data Catalog namespace as the raw dataset, so the description tables
sit alongside ``lamda_samples``/``lamda_files`` and can be joined by any
Iceberg reader (DuckDB, PyIceberg, Spark, Trino):

- ``lamda_feature_descriptions`` — one row per static-analysis token, with the
  config-specific ``feat_*`` column ids and the researched description /
  malware-detection-signal texts
- ``lamda_feature_categories`` — the Drebin feature sets (S1-S8) the tokens
  belong to
- ``lamda_column_glossary`` — the non-feature (metadata + provenance) columns
  of ``lamda_samples``

Reuses the R2 destination and catalog helpers from
``scripts/load_lamda_r2_iceberg.py``; the tables are tiny (thousands of rows),
so none of that pipeline's memory bounding is needed.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Iterator
from pathlib import Path

import dlt

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.load_lamda_r2_iceberg import (
    DEFAULT_DATASET_NAME,
    TABLE_FORMAT,
    apply_catalog_config,
    r2_bucket_url,
    r2_destination,
)

PIPELINE_NAME = "lamda_feature_descriptions_r2_iceberg"
DEFAULT_JSON = Path(__file__).resolve().parent.parent / "data" / "lamda_feature_descriptions.json"


def _lineage(payload: dict) -> dict:
    return {
        "dataset_id": payload["dataset_id"],
        "dataset_paper": payload["dataset_paper"],
        "generated_at": payload["generated_at"],
        "generator_version": payload["generator_version"],
    }


@dlt.resource(name="lamda_feature_descriptions", write_disposition="replace")
def feature_descriptions(payload: dict) -> Iterator[dict]:
    lineage = _lineage(payload)
    for feature in payload["features"]:
        yield {**feature, **lineage}


@dlt.resource(name="lamda_feature_categories", write_disposition="replace")
def feature_categories(payload: dict) -> Iterator[dict]:
    lineage = _lineage(payload)
    methodology = payload["feature_methodology"]
    for category in payload["categories"]:
        yield {**category, "feature_methodology": methodology, **lineage}


@dlt.resource(name="lamda_column_glossary", write_disposition="replace")
def column_glossary(payload: dict) -> Iterator[dict]:
    lineage = _lineage(payload)
    for column in payload["metadata_columns"]:
        yield {**column, **lineage}


def run_pipeline(
    json_path: Path = DEFAULT_JSON,
    dataset_name: str = DEFAULT_DATASET_NAME,
) -> None:
    with open(json_path, encoding="utf-8") as fh:
        payload = json.load(fh)

    apply_catalog_config()
    pipeline = dlt.pipeline(
        pipeline_name=PIPELINE_NAME,
        destination=r2_destination(),
        dataset_name=dataset_name,
    )
    load_info = pipeline.run(
        [
            feature_descriptions(payload),
            feature_categories(payload),
            column_glossary(payload),
        ],
        loader_file_format="parquet",
        table_format=TABLE_FORMAT,
    )
    print(load_info)

    row_counts = pipeline.last_trace.last_normalize_info.row_counts
    for table in ("lamda_feature_descriptions", "lamda_feature_categories", "lamda_column_glossary"):
        print(f"{table}: {row_counts.get(table, 0)} rows")
    print(
        f"Loaded feature descriptions into Iceberg namespace {dataset_name} "
        f"on {r2_bucket_url()}"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Load LAMDA feature descriptions into Cloudflare R2 as Iceberg tables "
            "registered in R2 Data Catalog."
        )
    )
    parser.add_argument(
        "--json-path",
        type=Path,
        default=DEFAULT_JSON,
        help="Path to the generated feature-description JSON.",
    )
    parser.add_argument(
        "--dataset-name",
        default=DEFAULT_DATASET_NAME,
        help="Destination Iceberg namespace. Defaults to raw_lamda, alongside lamda_samples.",
    )
    args = parser.parse_args()
    run_pipeline(json_path=args.json_path, dataset_name=args.dataset_name)


if __name__ == "__main__":
    main()
